//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: communication.proto

package dev.yanshouwang.camerax.communication;

@kotlin.jvm.JvmSynthetic
inline fun analysis(block: dev.yanshouwang.camerax.communication.AnalysisKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.Analysis =
  dev.yanshouwang.camerax.communication.AnalysisKt.Dsl._create(dev.yanshouwang.camerax.communication.Communication.Analysis.newBuilder()).apply { block() }._build()
object AnalysisKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.communication.Communication.Analysis.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.communication.Communication.Analysis.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.communication.Communication.Analysis = _builder.build()

    /**
     * <code>int32 key = 1;</code>
     */
    var key: kotlin.Int
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <code>int32 key = 1;</code>
     */
    fun clearKey() {
      _builder.clearKey()
    }

    /**
     * <code>bytes data = 2;</code>
     */
    var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <code>bytes data = 2;</code>
     */
    fun clearData() {
      _builder.clearData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.communication.Communication.Analysis.copy(block: dev.yanshouwang.camerax.communication.AnalysisKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.Analysis =
  dev.yanshouwang.camerax.communication.AnalysisKt.Dsl._create(this.toBuilder()).apply { block() }._build()
