//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: communication.proto

package dev.yanshouwang.camerax.communication;

@kotlin.jvm.JvmSynthetic
inline fun cameraParams(block: dev.yanshouwang.camerax.communication.CameraParamsKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.CameraParams =
  dev.yanshouwang.camerax.communication.CameraParamsKt.Dsl._create(dev.yanshouwang.camerax.communication.Communication.CameraParams.newBuilder()).apply { block() }._build()
object CameraParamsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.communication.Communication.CameraParams.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.communication.Communication.CameraParams.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.communication.Communication.CameraParams = _builder.build()

    /**
     * <code>bool has_torch = 1;</code>
     */
    var hasTorch: kotlin.Boolean
      @JvmName("getHasTorch")
      get() = _builder.getHasTorch()
      @JvmName("setHasTorch")
      set(value) {
        _builder.setHasTorch(value)
      }
    /**
     * <code>bool has_torch = 1;</code>
     */
    fun clearHasTorch() {
      _builder.clearHasTorch()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.communication.Communication.CameraParams.copy(block: dev.yanshouwang.camerax.communication.CameraParamsKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.CameraParams =
  dev.yanshouwang.camerax.communication.CameraParamsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
