//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: communication.proto

package dev.yanshouwang.camerax.communication;

@kotlin.jvm.JvmSynthetic
inline fun cameraBinding(block: dev.yanshouwang.camerax.communication.CameraBindingKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.CameraBinding =
  dev.yanshouwang.camerax.communication.CameraBindingKt.Dsl._create(dev.yanshouwang.camerax.communication.Communication.CameraBinding.newBuilder()).apply { block() }._build()
object CameraBindingKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.communication.Communication.CameraBinding.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.communication.Communication.CameraBinding.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.communication.Communication.CameraBinding = _builder.build()

    /**
     * <code>string key = 1;</code>
     */
    var key: kotlin.String
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <code>string key = 1;</code>
     */
    fun clearKey() {
      _builder.clearKey()
    }

    /**
     * <code>.communication.CameraArgs cameraArgs = 2;</code>
     */
    var cameraArgs: dev.yanshouwang.camerax.communication.Communication.CameraArgs
      @JvmName("getCameraArgs")
      get() = _builder.getCameraArgs()
      @JvmName("setCameraArgs")
      set(value) {
        _builder.setCameraArgs(value)
      }
    /**
     * <code>.communication.CameraArgs cameraArgs = 2;</code>
     */
    fun clearCameraArgs() {
      _builder.clearCameraArgs()
    }
    /**
     * <code>.communication.CameraArgs cameraArgs = 2;</code>
     * @return Whether the cameraArgs field is set.
     */
    fun hasCameraArgs(): kotlin.Boolean {
      return _builder.hasCameraArgs()
    }

    /**
     * <code>bool torchState = 3;</code>
     */
    var torchState: kotlin.Boolean
      @JvmName("getTorchState")
      get() = _builder.getTorchState()
      @JvmName("setTorchState")
      set(value) {
        _builder.setTorchState(value)
      }
    /**
     * <code>bool torchState = 3;</code>
     */
    fun clearTorchState() {
      _builder.clearTorchState()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.communication.Communication.CameraBinding.copy(block: dev.yanshouwang.camerax.communication.CameraBindingKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.CameraBinding =
  dev.yanshouwang.camerax.communication.CameraBindingKt.Dsl._create(this.toBuilder()).apply { block() }._build()
