//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: communication.proto

package dev.yanshouwang.camerax.communication;

@kotlin.jvm.JvmSynthetic
inline fun textureSize(block: dev.yanshouwang.camerax.communication.TextureSizeKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.TextureSize =
  dev.yanshouwang.camerax.communication.TextureSizeKt.Dsl._create(dev.yanshouwang.camerax.communication.Communication.TextureSize.newBuilder()).apply { block() }._build()
object TextureSizeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.communication.Communication.TextureSize.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.communication.Communication.TextureSize.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.communication.Communication.TextureSize = _builder.build()

    /**
     * <code>int32 width = 1;</code>
     */
    var width: kotlin.Int
      @JvmName("getWidth")
      get() = _builder.getWidth()
      @JvmName("setWidth")
      set(value) {
        _builder.setWidth(value)
      }
    /**
     * <code>int32 width = 1;</code>
     */
    fun clearWidth() {
      _builder.clearWidth()
    }

    /**
     * <code>int32 height = 2;</code>
     */
    var height: kotlin.Int
      @JvmName("getHeight")
      get() = _builder.getHeight()
      @JvmName("setHeight")
      set(value) {
        _builder.setHeight(value)
      }
    /**
     * <code>int32 height = 2;</code>
     */
    fun clearHeight() {
      _builder.clearHeight()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.communication.Communication.TextureSize.copy(block: dev.yanshouwang.camerax.communication.TextureSizeKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.TextureSize =
  dev.yanshouwang.camerax.communication.TextureSizeKt.Dsl._create(this.toBuilder()).apply { block() }._build()
