//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: communication.proto

package dev.yanshouwang.camerax.communication;

@kotlin.jvm.JvmSynthetic
inline fun torchState(block: dev.yanshouwang.camerax.communication.TorchStateKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.TorchState =
  dev.yanshouwang.camerax.communication.TorchStateKt.Dsl._create(dev.yanshouwang.camerax.communication.Communication.TorchState.newBuilder()).apply { block() }._build()
object TorchStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.communication.Communication.TorchState.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.communication.Communication.TorchState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.communication.Communication.TorchState = _builder.build()

    /**
     * <code>int32 key = 1;</code>
     */
    var key: kotlin.Int
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <code>int32 key = 1;</code>
     */
    fun clearKey() {
      _builder.clearKey()
    }

    /**
     * <code>bool state = 2;</code>
     */
    var state: kotlin.Boolean
      @JvmName("getState")
      get() = _builder.getState()
      @JvmName("setState")
      set(value) {
        _builder.setState(value)
      }
    /**
     * <code>bool state = 2;</code>
     */
    fun clearState() {
      _builder.clearState()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.communication.Communication.TorchState.copy(block: dev.yanshouwang.camerax.communication.TorchStateKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.TorchState =
  dev.yanshouwang.camerax.communication.TorchStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()
