//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: communication.proto

package dev.yanshouwang.camerax.communication;

@kotlin.jvm.JvmSynthetic
inline fun unbindArgs(block: dev.yanshouwang.camerax.communication.UnbindArgsKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.UnbindArgs =
  dev.yanshouwang.camerax.communication.UnbindArgsKt.Dsl._create(dev.yanshouwang.camerax.communication.Communication.UnbindArgs.newBuilder()).apply { block() }._build()
object UnbindArgsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.communication.Communication.UnbindArgs.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.communication.Communication.UnbindArgs.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.communication.Communication.UnbindArgs = _builder.build()

    /**
     * <code>string key = 1;</code>
     */
    var key: kotlin.String
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <code>string key = 1;</code>
     */
    fun clearKey() {
      _builder.clearKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.communication.Communication.UnbindArgs.copy(block: dev.yanshouwang.camerax.communication.UnbindArgsKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.UnbindArgs =
  dev.yanshouwang.camerax.communication.UnbindArgsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
