//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: communication.proto

package dev.yanshouwang.camerax.communication;

@kotlin.jvm.JvmSynthetic
inline fun viewParams(block: dev.yanshouwang.camerax.communication.ViewParamsKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.ViewParams =
  dev.yanshouwang.camerax.communication.ViewParamsKt.Dsl._create(dev.yanshouwang.camerax.communication.Communication.ViewParams.newBuilder()).apply { block() }._build()
object ViewParamsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.communication.Communication.ViewParams.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.communication.Communication.ViewParams.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.communication.Communication.ViewParams = _builder.build()

    /**
     * <code>int32 key = 1;</code>
     */
    var key: kotlin.Int
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <code>int32 key = 1;</code>
     */
    fun clearKey() {
      _builder.clearKey()
    }

    /**
     * <code>int32 texture_id = 2;</code>
     */
    var textureId: kotlin.Int
      @JvmName("getTextureId")
      get() = _builder.getTextureId()
      @JvmName("setTextureId")
      set(value) {
        _builder.setTextureId(value)
      }
    /**
     * <code>int32 texture_id = 2;</code>
     */
    fun clearTextureId() {
      _builder.clearTextureId()
    }

    /**
     * <code>.communication.TextureSize size = 3;</code>
     */
    var size: dev.yanshouwang.camerax.communication.Communication.TextureSize
      @JvmName("getSize")
      get() = _builder.getSize()
      @JvmName("setSize")
      set(value) {
        _builder.setSize(value)
      }
    /**
     * <code>.communication.TextureSize size = 3;</code>
     */
    fun clearSize() {
      _builder.clearSize()
    }
    /**
     * <code>.communication.TextureSize size = 3;</code>
     * @return Whether the size field is set.
     */
    fun hasSize(): kotlin.Boolean {
      return _builder.hasSize()
    }

    /**
     * <code>.communication.Rotation rotation = 4;</code>
     */
    var rotation: dev.yanshouwang.camerax.communication.Communication.Rotation
      @JvmName("getRotation")
      get() = _builder.getRotation()
      @JvmName("setRotation")
      set(value) {
        _builder.setRotation(value)
      }
    /**
     * <code>.communication.Rotation rotation = 4;</code>
     */
    fun clearRotation() {
      _builder.clearRotation()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.communication.Communication.ViewParams.copy(block: dev.yanshouwang.camerax.communication.ViewParamsKt.Dsl.() -> Unit): dev.yanshouwang.camerax.communication.Communication.ViewParams =
  dev.yanshouwang.camerax.communication.ViewParamsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
