//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax;

@kotlin.jvm.JvmSynthetic
public inline fun cameraValue(block: dev.yanshouwang.camerax.CameraValueKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.CameraValue =
  dev.yanshouwang.camerax.CameraValueKt.Dsl._create(dev.yanshouwang.camerax.Messages.CameraValue.newBuilder()).apply { block() }._build()
public object CameraValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.yanshouwang.camerax.Messages.CameraValue.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.Messages.CameraValue.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.Messages.CameraValue = _builder.build()

    /**
     * <code>string uuid = 1;</code>
     */
    public var uuid: kotlin.String
      @JvmName("getUuid")
      get() = _builder.getUuid()
      @JvmName("setUuid")
      set(value) {
        _builder.setUuid(value)
      }
    /**
     * <code>string uuid = 1;</code>
     */
    public fun clearUuid() {
      _builder.clearUuid()
    }

    /**
     * <code>.messages.TextureValue texture_value = 2;</code>
     */
    public var textureValue: dev.yanshouwang.camerax.Messages.TextureValue
      @JvmName("getTextureValue")
      get() = _builder.getTextureValue()
      @JvmName("setTextureValue")
      set(value) {
        _builder.setTextureValue(value)
      }
    /**
     * <code>.messages.TextureValue texture_value = 2;</code>
     */
    public fun clearTextureValue() {
      _builder.clearTextureValue()
    }
    /**
     * <code>.messages.TextureValue texture_value = 2;</code>
     * @return Whether the textureValue field is set.
     */
    public fun hasTextureValue(): kotlin.Boolean {
      return _builder.hasTextureValue()
    }

    /**
     * <code>.messages.TorchValue torch_value = 3;</code>
     */
    public var torchValue: dev.yanshouwang.camerax.Messages.TorchValue
      @JvmName("getTorchValue")
      get() = _builder.getTorchValue()
      @JvmName("setTorchValue")
      set(value) {
        _builder.setTorchValue(value)
      }
    /**
     * <code>.messages.TorchValue torch_value = 3;</code>
     */
    public fun clearTorchValue() {
      _builder.clearTorchValue()
    }
    /**
     * <code>.messages.TorchValue torch_value = 3;</code>
     * @return Whether the torchValue field is set.
     */
    public fun hasTorchValue(): kotlin.Boolean {
      return _builder.hasTorchValue()
    }

    /**
     * <code>.messages.ZoomValue zoom_value = 4;</code>
     */
    public var zoomValue: dev.yanshouwang.camerax.Messages.ZoomValue
      @JvmName("getZoomValue")
      get() = _builder.getZoomValue()
      @JvmName("setZoomValue")
      set(value) {
        _builder.setZoomValue(value)
      }
    /**
     * <code>.messages.ZoomValue zoom_value = 4;</code>
     */
    public fun clearZoomValue() {
      _builder.clearZoomValue()
    }
    /**
     * <code>.messages.ZoomValue zoom_value = 4;</code>
     * @return Whether the zoomValue field is set.
     */
    public fun hasZoomValue(): kotlin.Boolean {
      return _builder.hasZoomValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.yanshouwang.camerax.Messages.CameraValue.copy(block: dev.yanshouwang.camerax.CameraValueKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.CameraValue =
  dev.yanshouwang.camerax.CameraValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()
