//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax;

@kotlin.jvm.JvmSynthetic
public inline fun cameraControllerZoomCommandArguments(block: dev.yanshouwang.camerax.CameraControllerZoomCommandArgumentsKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.CameraControllerZoomCommandArguments =
  dev.yanshouwang.camerax.CameraControllerZoomCommandArgumentsKt.Dsl._create(dev.yanshouwang.camerax.Messages.CameraControllerZoomCommandArguments.newBuilder()).apply { block() }._build()
public object CameraControllerZoomCommandArgumentsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.yanshouwang.camerax.Messages.CameraControllerZoomCommandArguments.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.Messages.CameraControllerZoomCommandArguments.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.Messages.CameraControllerZoomCommandArguments = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>double value = 2;</code>
     */
    public var value: kotlin.Double
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <code>double value = 2;</code>
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.yanshouwang.camerax.Messages.CameraControllerZoomCommandArguments.copy(block: dev.yanshouwang.camerax.CameraControllerZoomCommandArgumentsKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.CameraControllerZoomCommandArguments =
  dev.yanshouwang.camerax.CameraControllerZoomCommandArgumentsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
