//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax;

@kotlin.jvm.JvmSynthetic
public inline fun cameraControllerImageProxiedEventArguments(block: dev.yanshouwang.camerax.CameraControllerImageProxiedEventArgumentsKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.CameraControllerImageProxiedEventArguments =
  dev.yanshouwang.camerax.CameraControllerImageProxiedEventArgumentsKt.Dsl._create(dev.yanshouwang.camerax.Messages.CameraControllerImageProxiedEventArguments.newBuilder()).apply { block() }._build()
public object CameraControllerImageProxiedEventArgumentsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.yanshouwang.camerax.Messages.CameraControllerImageProxiedEventArguments.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.Messages.CameraControllerImageProxiedEventArguments.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.Messages.CameraControllerImageProxiedEventArguments = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>.messages.ImageProxy image_proxy = 2;</code>
     */
    public var imageProxy: dev.yanshouwang.camerax.Messages.ImageProxy
      @JvmName("getImageProxy")
      get() = _builder.getImageProxy()
      @JvmName("setImageProxy")
      set(value) {
        _builder.setImageProxy(value)
      }
    /**
     * <code>.messages.ImageProxy image_proxy = 2;</code>
     */
    public fun clearImageProxy() {
      _builder.clearImageProxy()
    }
    /**
     * <code>.messages.ImageProxy image_proxy = 2;</code>
     * @return Whether the imageProxy field is set.
     */
    public fun hasImageProxy(): kotlin.Boolean {
      return _builder.hasImageProxy()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.yanshouwang.camerax.Messages.CameraControllerImageProxiedEventArguments.copy(block: dev.yanshouwang.camerax.CameraControllerImageProxiedEventArgumentsKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.CameraControllerImageProxiedEventArguments =
  dev.yanshouwang.camerax.CameraControllerImageProxiedEventArgumentsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
