//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax;

@kotlin.jvm.JvmSynthetic
public inline fun imageProxyCloseCommandArguments(block: dev.yanshouwang.camerax.ImageProxyCloseCommandArgumentsKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.ImageProxyCloseCommandArguments =
  dev.yanshouwang.camerax.ImageProxyCloseCommandArgumentsKt.Dsl._create(dev.yanshouwang.camerax.Messages.ImageProxyCloseCommandArguments.newBuilder()).apply { block() }._build()
public object ImageProxyCloseCommandArgumentsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.yanshouwang.camerax.Messages.ImageProxyCloseCommandArguments.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.Messages.ImageProxyCloseCommandArguments.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.Messages.ImageProxyCloseCommandArguments = _builder.build()

    /**
     * <code>string controller_id = 1;</code>
     */
    public var controllerId: kotlin.String
      @JvmName("getControllerId")
      get() = _builder.getControllerId()
      @JvmName("setControllerId")
      set(value) {
        _builder.setControllerId(value)
      }
    /**
     * <code>string controller_id = 1;</code>
     */
    public fun clearControllerId() {
      _builder.clearControllerId()
    }

    /**
     * <code>string id = 2;</code>
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 2;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.yanshouwang.camerax.Messages.ImageProxyCloseCommandArguments.copy(block: dev.yanshouwang.camerax.ImageProxyCloseCommandArgumentsKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.ImageProxyCloseCommandArguments =
  dev.yanshouwang.camerax.ImageProxyCloseCommandArgumentsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
