//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax;

@kotlin.jvm.JvmSynthetic
inline fun methodArguments(block: dev.yanshouwang.camerax.MethodArgumentsKt.Dsl.() -> Unit): dev.yanshouwang.camerax.Messages.MethodArguments =
  dev.yanshouwang.camerax.MethodArgumentsKt.Dsl._create(dev.yanshouwang.camerax.Messages.MethodArguments.newBuilder()).apply { block() }._build()
object MethodArgumentsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.Messages.MethodArguments.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.Messages.MethodArguments.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.Messages.MethodArguments = _builder.build()

    /**
     * <code>.messages.MethodCategory category = 1;</code>
     */
    var category: dev.yanshouwang.camerax.Messages.MethodCategory
      @JvmName("getCategory")
      get() = _builder.getCategory()
      @JvmName("setCategory")
      set(value) {
        _builder.setCategory(value)
      }
    /**
     * <code>.messages.MethodCategory category = 1;</code>
     */
    fun clearCategory() {
      _builder.clearCategory()
    }

    /**
     * <code>.messages.CameraSelector selector = 2;</code>
     */
    var selector: dev.yanshouwang.camerax.Messages.CameraSelector
      @JvmName("getSelector")
      get() = _builder.getSelector()
      @JvmName("setSelector")
      set(value) {
        _builder.setSelector(value)
      }
    /**
     * <code>.messages.CameraSelector selector = 2;</code>
     */
    fun clearSelector() {
      _builder.clearSelector()
    }
    /**
     * <code>.messages.CameraSelector selector = 2;</code>
     * @return Whether the selector field is set.
     */
    fun hasSelector(): kotlin.Boolean {
      return _builder.hasSelector()
    }

    /**
     * <code>string uuid = 3;</code>
     */
    var uuid: kotlin.String
      @JvmName("getUuid")
      get() = _builder.getUuid()
      @JvmName("setUuid")
      set(value) {
        _builder.setUuid(value)
      }
    /**
     * <code>string uuid = 3;</code>
     */
    fun clearUuid() {
      _builder.clearUuid()
    }

    /**
     * <code>bool torch_state = 4;</code>
     */
    var torchState: kotlin.Boolean
      @JvmName("getTorchState")
      get() = _builder.getTorchState()
      @JvmName("setTorchState")
      set(value) {
        _builder.setTorchState(value)
      }
    /**
     * <code>bool torch_state = 4;</code>
     */
    fun clearTorchState() {
      _builder.clearTorchState()
    }

    /**
     * <code>double zoom_value = 5;</code>
     */
    var zoomValue: kotlin.Double
      @JvmName("getZoomValue")
      get() = _builder.getZoomValue()
      @JvmName("setZoomValue")
      set(value) {
        _builder.setZoomValue(value)
      }
    /**
     * <code>double zoom_value = 5;</code>
     */
    fun clearZoomValue() {
      _builder.clearZoomValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.Messages.MethodArguments.copy(block: dev.yanshouwang.camerax.MethodArgumentsKt.Dsl.() -> Unit): dev.yanshouwang.camerax.Messages.MethodArguments =
  dev.yanshouwang.camerax.MethodArgumentsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
