//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax;

@kotlin.jvm.JvmSynthetic
public inline fun offset(block: dev.yanshouwang.camerax.OffsetKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.Offset =
  dev.yanshouwang.camerax.OffsetKt.Dsl._create(dev.yanshouwang.camerax.Messages.Offset.newBuilder()).apply { block() }._build()
public object OffsetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.yanshouwang.camerax.Messages.Offset.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.Messages.Offset.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.Messages.Offset = _builder.build()

    /**
     * <code>double x = 1;</code>
     */
    public var x: kotlin.Double
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * <code>double x = 1;</code>
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * <code>double y = 2;</code>
     */
    public var y: kotlin.Double
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * <code>double y = 2;</code>
     */
    public fun clearY() {
      _builder.clearY()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.yanshouwang.camerax.Messages.Offset.copy(block: dev.yanshouwang.camerax.OffsetKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.Offset =
  dev.yanshouwang.camerax.OffsetKt.Dsl._create(this.toBuilder()).apply { block() }._build()
