//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax;

@kotlin.jvm.JvmSynthetic
public inline fun textureValue(block: dev.yanshouwang.camerax.TextureValueKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.TextureValue =
  dev.yanshouwang.camerax.TextureValueKt.Dsl._create(dev.yanshouwang.camerax.Messages.TextureValue.newBuilder()).apply { block() }._build()
public object TextureValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.yanshouwang.camerax.Messages.TextureValue.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.Messages.TextureValue.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.Messages.TextureValue = _builder.build()

    /**
     * <code>int32 id = 1;</code>
     */
    public var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>int32 id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>int32 width = 2;</code>
     */
    public var width: kotlin.Int
      @JvmName("getWidth")
      get() = _builder.getWidth()
      @JvmName("setWidth")
      set(value) {
        _builder.setWidth(value)
      }
    /**
     * <code>int32 width = 2;</code>
     */
    public fun clearWidth() {
      _builder.clearWidth()
    }

    /**
     * <code>int32 height = 3;</code>
     */
    public var height: kotlin.Int
      @JvmName("getHeight")
      get() = _builder.getHeight()
      @JvmName("setHeight")
      set(value) {
        _builder.setHeight(value)
      }
    /**
     * <code>int32 height = 3;</code>
     */
    public fun clearHeight() {
      _builder.clearHeight()
    }

    /**
     * <code>int32 quarter_turns = 4;</code>
     */
    public var quarterTurns: kotlin.Int
      @JvmName("getQuarterTurns")
      get() = _builder.getQuarterTurns()
      @JvmName("setQuarterTurns")
      set(value) {
        _builder.setQuarterTurns(value)
      }
    /**
     * <code>int32 quarter_turns = 4;</code>
     */
    public fun clearQuarterTurns() {
      _builder.clearQuarterTurns()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.yanshouwang.camerax.Messages.TextureValue.copy(block: dev.yanshouwang.camerax.TextureValueKt.Dsl.() -> kotlin.Unit): dev.yanshouwang.camerax.Messages.TextureValue =
  dev.yanshouwang.camerax.TextureValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()
