//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax.message;

@kotlin.jvm.JvmSynthetic
inline fun event(block: dev.yanshouwang.camerax.message.EventKt.Dsl.() -> Unit): dev.yanshouwang.camerax.message.Messages.Event =
  dev.yanshouwang.camerax.message.EventKt.Dsl._create(dev.yanshouwang.camerax.message.Messages.Event.newBuilder()).apply { block() }._build()
object EventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.message.Messages.Event.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.message.Messages.Event.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.message.Messages.Event = _builder.build()

    /**
     * <code>string key = 1;</code>
     */
    var key: kotlin.String
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <code>string key = 1;</code>
     */
    fun clearKey() {
      _builder.clearKey()
    }

    /**
     * <code>.messages.EventCategory category = 2;</code>
     */
    var category: dev.yanshouwang.camerax.message.Messages.EventCategory
      @JvmName("getCategory")
      get() = _builder.getCategory()
      @JvmName("setCategory")
      set(value) {
        _builder.setCategory(value)
      }
    /**
     * <code>.messages.EventCategory category = 2;</code>
     */
    fun clearCategory() {
      _builder.clearCategory()
    }

    /**
     * <code>int32 quarterTurns = 3;</code>
     */
    var quarterTurns: kotlin.Int
      @JvmName("getQuarterTurns")
      get() = _builder.getQuarterTurns()
      @JvmName("setQuarterTurns")
      set(value) {
        _builder.setQuarterTurns(value)
      }
    /**
     * <code>int32 quarterTurns = 3;</code>
     */
    fun clearQuarterTurns() {
      _builder.clearQuarterTurns()
    }
    /**
     * <code>int32 quarterTurns = 3;</code>
     * @return Whether the quarterTurns field is set.
     */
    fun hasQuarterTurns(): kotlin.Boolean {
      return _builder.hasQuarterTurns()
    }

    /**
     * <code>bool torch_state = 4;</code>
     */
    var torchState: kotlin.Boolean
      @JvmName("getTorchState")
      get() = _builder.getTorchState()
      @JvmName("setTorchState")
      set(value) {
        _builder.setTorchState(value)
      }
    /**
     * <code>bool torch_state = 4;</code>
     */
    fun clearTorchState() {
      _builder.clearTorchState()
    }
    /**
     * <code>bool torch_state = 4;</code>
     * @return Whether the torchState field is set.
     */
    fun hasTorchState(): kotlin.Boolean {
      return _builder.hasTorchState()
    }

    /**
     * <code>double zoom_value = 5;</code>
     */
    var zoomValue: kotlin.Double
      @JvmName("getZoomValue")
      get() = _builder.getZoomValue()
      @JvmName("setZoomValue")
      set(value) {
        _builder.setZoomValue(value)
      }
    /**
     * <code>double zoom_value = 5;</code>
     */
    fun clearZoomValue() {
      _builder.clearZoomValue()
    }
    /**
     * <code>double zoom_value = 5;</code>
     * @return Whether the zoomValue field is set.
     */
    fun hasZoomValue(): kotlin.Boolean {
      return _builder.hasZoomValue()
    }

    /**
     * <code>.messages.ImageProxy image = 6;</code>
     */
    var image: dev.yanshouwang.camerax.message.Messages.ImageProxy
      @JvmName("getImage")
      get() = _builder.getImage()
      @JvmName("setImage")
      set(value) {
        _builder.setImage(value)
      }
    /**
     * <code>.messages.ImageProxy image = 6;</code>
     */
    fun clearImage() {
      _builder.clearImage()
    }
    /**
     * <code>.messages.ImageProxy image = 6;</code>
     * @return Whether the image field is set.
     */
    fun hasImage(): kotlin.Boolean {
      return _builder.hasImage()
    }
    val stubCase: dev.yanshouwang.camerax.message.Messages.Event.StubCase
      @JvmName("getStubCase")
      get() = _builder.getStubCase()

    fun clearStub() {
      _builder.clearStub()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.message.Messages.Event.copy(block: dev.yanshouwang.camerax.message.EventKt.Dsl.() -> Unit): dev.yanshouwang.camerax.message.Messages.Event =
  dev.yanshouwang.camerax.message.EventKt.Dsl._create(this.toBuilder()).apply { block() }._build()
