//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax.message;

@kotlin.jvm.JvmSynthetic
inline fun imageProxy(block: dev.yanshouwang.camerax.message.ImageProxyKt.Dsl.() -> Unit): dev.yanshouwang.camerax.message.Messages.ImageProxy =
  dev.yanshouwang.camerax.message.ImageProxyKt.Dsl._create(dev.yanshouwang.camerax.message.Messages.ImageProxy.newBuilder()).apply { block() }._build()
object ImageProxyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.message.Messages.ImageProxy.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.message.Messages.ImageProxy.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.message.Messages.ImageProxy = _builder.build()

    /**
     * <code>string key = 1;</code>
     */
    var key: kotlin.String
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <code>string key = 1;</code>
     */
    fun clearKey() {
      _builder.clearKey()
    }

    /**
     * <code>bytes data = 2;</code>
     */
    var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <code>bytes data = 2;</code>
     */
    fun clearData() {
      _builder.clearData()
    }

    /**
     * <code>int32 width = 3;</code>
     */
    var width: kotlin.Int
      @JvmName("getWidth")
      get() = _builder.getWidth()
      @JvmName("setWidth")
      set(value) {
        _builder.setWidth(value)
      }
    /**
     * <code>int32 width = 3;</code>
     */
    fun clearWidth() {
      _builder.clearWidth()
    }

    /**
     * <code>int32 height = 4;</code>
     */
    var height: kotlin.Int
      @JvmName("getHeight")
      get() = _builder.getHeight()
      @JvmName("setHeight")
      set(value) {
        _builder.setHeight(value)
      }
    /**
     * <code>int32 height = 4;</code>
     */
    fun clearHeight() {
      _builder.clearHeight()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.message.Messages.ImageProxy.copy(block: dev.yanshouwang.camerax.message.ImageProxyKt.Dsl.() -> Unit): dev.yanshouwang.camerax.message.Messages.ImageProxy =
  dev.yanshouwang.camerax.message.ImageProxyKt.Dsl._create(this.toBuilder()).apply { block() }._build()
