//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

package dev.yanshouwang.camerax.message;

@kotlin.jvm.JvmSynthetic
inline fun openArguments(block: dev.yanshouwang.camerax.message.OpenArgumentsKt.Dsl.() -> Unit): dev.yanshouwang.camerax.message.Messages.OpenArguments =
  dev.yanshouwang.camerax.message.OpenArgumentsKt.Dsl._create(dev.yanshouwang.camerax.message.Messages.OpenArguments.newBuilder()).apply { block() }._build()
object OpenArgumentsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: dev.yanshouwang.camerax.message.Messages.OpenArguments.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: dev.yanshouwang.camerax.message.Messages.OpenArguments.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): dev.yanshouwang.camerax.message.Messages.OpenArguments = _builder.build()

    /**
     * <code>.messages.CameraSelector selector = 1;</code>
     */
    var selector: dev.yanshouwang.camerax.message.Messages.CameraSelector
      @JvmName("getSelector")
      get() = _builder.getSelector()
      @JvmName("setSelector")
      set(value) {
        _builder.setSelector(value)
      }
    /**
     * <code>.messages.CameraSelector selector = 1;</code>
     */
    fun clearSelector() {
      _builder.clearSelector()
    }
    /**
     * <code>.messages.CameraSelector selector = 1;</code>
     * @return Whether the selector field is set.
     */
    fun hasSelector(): kotlin.Boolean {
      return _builder.hasSelector()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun dev.yanshouwang.camerax.message.Messages.OpenArguments.copy(block: dev.yanshouwang.camerax.message.OpenArgumentsKt.Dsl.() -> Unit): dev.yanshouwang.camerax.message.Messages.OpenArguments =
  dev.yanshouwang.camerax.message.OpenArgumentsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
